steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download Build Artifacts
    inputs:
      buildType: "current"
      downloadType: "single"
      artifactName: "drop"
      downloadPath: "$(System.ArtifactsDirectory)"

  - task: LambdaDeployFunction@1
    displayName: "Deploy Lambda Function"
    inputs:
      awsCredentials: "Dewald-AWS"
      regionName: "$(AWS_REGION)"
      deploymentMode: "codeandconfiguration"
      functionName: "getSettings"
      description: "From AzureDevops"
      functionHandler: "GetSettings::GetSettings.Settings::FetchAll"
      runtime: "dotnet6"
      codeLocation: "localfile"
      localZipFile: "$(Build.ArtifactStagingDirectory)/drop/GetSettings.zip"
      roleARN: "$(AWS_ROLE)"
      timeout: 30
